const navRoutes = {
    'london-property-maintenance': 'london-property-maintenance',
    'birmingham-property-maintenance': 'birmingham-property-maintenance',
    'manchester-property-maintenance': 'manchester-property-maintenance',
    'liverpool-property-maintenance': 'liverpool-property-maintenance',
    'leeds-property-maintenance': 'leeds-property-maintenance',
    'glasgow-property-maintenance': 'glasgow-property-maintenance',
    'sheffield-property-maintenance': 'sheffield-property-maintenance',
    'edinburgh-property-maintenance': 'edinburgh-property-maintenance',
    'bristol-property-maintenance': 'bristol-property-maintenance',
    'cardiff-property-maintenance': 'cardiff-property-maintenance',
    'nottingham-property-maintenance': 'nottingham-property-maintenance',
    'leicester-property-maintenance': 'leicester-property-maintenance',
    'newcastle-property-maintenance': 'newcastle-property-maintenance',
    'coventry-property-maintenance': 'coventry-property-maintenance',
    'kingston-upon-hull-property-maintenance': 'kingston-upon-hull-property-maintenance',
    'bradford-property-maintenance': 'bradford-property-maintenance',
    'belfast-property-maintenance': 'belfast-property-maintenance',
    'stoke-on-trent-property-maintenance': 'stoke-on-trent-property-maintenance',
    'wolverhampton-property-maintenance': 'wolverhampton-property-maintenance',
    'plymouth-property-maintenance': 'plymouth-property-maintenance',
    'derby-property-maintenance': 'derby-property-maintenance',
    'southampton-property-maintenance': 'southampton-property-maintenance',
    'portsmouth-property-maintenance': 'portsmouth-property-maintenance',
    'swansea-property-maintenance': 'swansea-property-maintenance',
    'oxford-property-maintenance': 'oxford-property-maintenance',
    'cambridge-property-maintenance': 'cambridge-property-maintenance',
    'york-property-maintenance': 'york-property-maintenance',
    'exeter-property-maintenance': 'exeter-property-maintenance',
    'chelmsford-property-maintenance': 'chelmsford-property-maintenance',
    'canterbury-property-maintenance': 'canterbury-property-maintenance',
    'london-handyman': 'london-handyman',
    'manchester-handyman': 'manchester-handyman',
    'birmingham-handyman': 'birmingham-handyman',
    'bristol-handyman': 'bristol-handyman',
    'liverpool-handyman': 'liverpool-handyman'
};

module.exports = navRoutes;
